name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Load Build Cache
      uses: Swatinem/rust-cache@v1
    
    - name: Run Cargo Check
      uses: actions-rs/cargo@v1
      with:
        command: check
